-- MySQL Script generated by MySQL Workbench
-- Wed Mar 17 19:28:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id` INT NOT NULL,
  `nom d'utilisateur` VARCHAR(45) NOT NULL,
  `num-téléphone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` INT NOT NULL,
  `addresse` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `num-téléphone_UNIQUE` (`num-téléphone` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produit` (
  `référence` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `details_produit` VARCHAR(45) NULL,
  `quantité` INT NULL,
  `prix` INT NOT NULL,
  PRIMARY KEY (`référence`),
  UNIQUE INDEX `prix_UNIQUE` (`prix` ASC) VISIBLE)
ENGINE = InnoDB
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `mydb`.`confirmer_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`confirmer_commande` (
  `confirmation_id` INT NOT NULL,
  `nom d'utilisateur` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `numtélé` INT NOT NULL,
  `typepaiment` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`confirmation_id`));


-- -----------------------------------------------------
-- Table `mydb`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commande` (
  `commande_id` INT NOT NULL,
  `description_cmd` VARCHAR(255) NULL,
  `total_cmd` INT NOT NULL,
  `date_cmd` DATETIME(45) NOT NULL,
  `référence` INT NOT NULL,
  `id` INT NOT NULL,
  `etat` VARCHAR(45) NOT NULL,
  `confirmation_id` INT NOT NULL,
  PRIMARY KEY (`commande_id`),
  INDEX `référence_idx` (`référence` ASC) VISIBLE,
  INDEX `CIN_idx` (`id` ASC) VISIBLE,
  UNIQUE INDEX `confirmation_id_UNIQUE` (`confirmation_id` ASC) VISIBLE,
  CONSTRAINT `référence`
    FOREIGN KEY (`référence`)
    REFERENCES `mydb`.`produit` (`référence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CIN`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `confirmaton_id`
    FOREIGN KEY (`confirmation_id`)
    REFERENCES `mydb`.`confirmer_commande` (`confirmation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facture` (
  `facture_réf` INT NOT NULL,
  `total` INT NOT NULL,
  `date_facture` DATETIME(45) NULL,
  `tva` INT NULL,
  `remise` INT NULL,
  `commande_id` INT NOT NULL,
  PRIMARY KEY (`facture_réf`),
  UNIQUE INDEX `commande_id_UNIQUE` (`commande_id` ASC) VISIBLE,
  CONSTRAINT `commande_id`
    FOREIGN KEY (`commande_id`)
    REFERENCES `mydb`.`commande` (`commande_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`livraision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livraision` (
  `livraision_id` INT NOT NULL,
  `livdate` DATE NOT NULL,
  `livdescription` VARCHAR(45) NULL,
  `commande_id` INT NOT NULL,
  PRIMARY KEY (`livraision_id`),
  INDEX `commande_id_idx` (`commande_id` ASC) VISIBLE,
  CONSTRAINT `commande_id`
    FOREIGN KEY (`commande_id`)
    REFERENCES `mydb`.`commande` (`commande_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
