-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1
-- Généré le : dim. 02 mai 2021 à 22:25
-- Version du serveur :  10.4.18-MariaDB
-- Version de PHP : 8.0.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `techstore`
--

-- --------------------------------------------------------

--
-- Structure de la table `client`
--

CREATE TABLE `client` (
  `id` int(11) NOT NULL,
  `nutilisateur` varchar(45) NOT NULL,
  `ntelephone` varchar(45) NOT NULL,
  `email` varchar(45) NOT NULL,
  `password` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Déchargement des données de la table `client`
--

INSERT INTO `client` (`id`, `nutilisateur`, `ntelephone`, `email`, `password`) VALUES
(1, 'aaa', '92690722', 'azerty@gmail.com', 'azerty'),
(2, 'a', '11223344', 'a@a.a', 'a'),
(4, '', '', '', ''),
(7, 'ena', '87654322', 'ena@ena.ena', 'ena');

-- --------------------------------------------------------

--
-- Structure de la table `commande`
--

CREATE TABLE `commande` (
  `commande_id` int(11) NOT NULL,
  `référence` int(11) NOT NULL,
  `pnom` varchar(50) NOT NULL,
  `id` int(11) NOT NULL,
  `detail_c` varchar(255) DEFAULT NULL,
  `total_cmd` int(11) NOT NULL,
  `date_cmd` varchar(10) NOT NULL,
  `etat` varchar(45) NOT NULL,
  `payement` varchar(50) NOT NULL,
  `adresse` varchar(45) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Déchargement des données de la table `commande`
--

INSERT INTO `commande` (`commande_id`, `référence`, `pnom`, `id`, `detail_c`, `total_cmd`, `date_cmd`, `etat`, `payement`, `adresse`) VALUES
(5, 30, 'Huawei FreeBuds Pro', 2, '12', 8388, '2021-05-02', 'traitement en cour', 'choisir type payement...', 'BA');

-- --------------------------------------------------------

--
-- Structure de la table `produit`
--

CREATE TABLE `produit` (
  `référence` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `type` varchar(45) DEFAULT NULL,
  `details` text DEFAULT NULL,
  `description` text DEFAULT NULL,
  `quantité` int(11) DEFAULT NULL,
  `prix` int(11) DEFAULT NULL,
  `image` text DEFAULT NULL,
  `images` text DEFAULT NULL,
  `caracteristique` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Déchargement des données de la table `produit`
--

INSERT INTO `produit` (`référence`, `name`, `type`, `details`, `description`, `quantité`, `prix`, `image`, `images`, `caracteristique`) VALUES
(1, 'HP 15S-EQ1003NK', 'ordinateur', 'Ecran 15.6 pouce HD LED - Processeur AMD Dual Core 3020e, up to 2.6 Ghz, 4 Mo de memoire cache - 4 Go de memoire - Disque 256 Go SSD PCIe NVMe M.2 - Carte graphique AMD Radeon Integree - Lecteur de cartes - Webcam HD 720p HP True Vision - Wifi - Bluetooth - HDMI - 1x USB Type C - 2x USB 3.1 - Windows 10 - Couleur Noir - Garantie 1 an ', 'PC PORTABLE HP 15S-EQ1003NK / AMD DUAL CORE / 4 GO / NOIR', 0, 990, 'https://www.tunisianet.com.tn/194310-large/pc-portable-hp-15s-eq1003nk-amd-dual-core-4-go-noir.jpg', 'https://www.tunisianet.com.tn/194308-large/pc-portable-hp-15s-eq1003nk-amd-dual-core-4-go-noir.jpg,https://www.tunisianet.com.tn/194309-large/pc-portable-hp-15s-eq1003nk-amd-dual-core-4-go-noir.jpg,https://www.tunisianet.com.tn/194311-large/pc-portable-hp-15s-eq1003nk-amd-dual-core-4-go-noir.jpg,https://www.tunisianet.com.tn/194312-large/pc-portable-hp-15s-eq1003nk-amd-dual-core-4-go-noir.jpg', '[{\\\"champ\\\":\\\"Systeme D exploitation\\\",\\\"valeur\\\":\\\"Windows 10\\\"},{\\\"champ\\\":\\\"Processeur\\\",\\\"valeur\\\":\\\"AMD Dual Core\\\"},{\\\"champ\\\":\\\"Ref processeur\\\",\\\"valeur\\\":\\\"AMD Dual Core 3020e, Up To 2.6 Ghz, 4 Mo De Memoire Cache\\\"},{\\\"champ\\\":\\\"memoire\\\",\\\"valeur\\\":\\\"4 Go\\\"},{\\\"champ\\\":\\\"Disque Dur\\\",\\\"valeur\\\":\\\"256 Go SSD\\\"},{\\\"champ\\\":\\\"Carte Graphique\\\",\\\"valeur\\\":\\\"Graphique Integree\\\"},{\\\"champ\\\":\\\"Ref Carte Graphique\\\",\\\"valeur\\\":\\\"AMD Radeon Integree\\\"},{\\\"champ\\\":\\\"Taille Ecran\\\",\\\"valeur\\\":\\\"15.6\\\"},{\\\"champ\\\":\\\"Type Ecran\\\",\\\"valeur\\\":\\\"HD\\\"},{\\\"champ\\\":\\\"Ecran Tactile\\\",\\\"valeur\\\":\\\"Non\\\"},{\\\"champ\\\":\\\"lecteurs\\\",\\\"valeur\\\":\\\"Lecteur De Cartes\\\"},{\\\"champ\\\":\\\"Reseau\\\",\\\"valeur\\\":\\\"WiFi - Bluetooth\\\"},{\\\"champ\\\":\\\"Camera\\\",\\\"valeur\\\":\\\"Webcam HD\\\"},{\\\"champ\\\":\\\"Garantie\\\",\\\"valeur\\\":\\\"1 An\\\"}]'),
(2, 'HP PRO 300 G3', 'ordinateur', 'PC DE BUREAU HP PRO 300 G3 / DUAL CORE GOLD / 12 GO', 'Processeur Intel Pentium Dual Core G5420, 3.8 Ghz, 4 Mo de memoire cache - Memoire 12 Go - Disque 1 To - Carte graphique Intel Graphics  UHD 610 - Graveur DVD - 4x USB 3.1 - HDMI - VGA  - Garantie 1 an', 0, 858, 'https://www.tunisianet.com.tn/177138-large/pc-de-bureau-hp-pro-300-g3-dual-core-gold-12-go.jpg', NULL, '[{\\\"champ\\\":\\\"Systeme D exploitation\\\",\\\"valeur\\\":\\\"FreeDos\\\"},{\\\"champ\\\":\\\"Processeur\\\",\\\"valeur\\\":\\\"Intel Pentium Dual Core\\\"},{\\\"champ\\\":\\\"Ref processeur\\\",\\\"valeur\\\":\\\"Intel Pentium Gold Dual Core G5420, 3.8 GHz, 4 Mo De Memoire Cache\\\"},{\\\"champ\\\":\\\"memoire\\\",\\\"valeur\\\":\\\"12 Go\\\"},{\\\"champ\\\":\\\"Disque Dur\\\",\\\"valeur\\\":\\\"1 To\\\"},{\\\"champ\\\":\\\"Carte Graphique\\\",\\\"valeur\\\":\\\"Graphique Integree\\\"},{\\\"champ\\\":\\\"Ref Carte Graphique\\\",\\\"valeur\\\":\\\"Intel UHD 610\\\"},{\\\"champ\\\":\\\"Taille Ecran\\\",\\\"valeur\\\":\\\"\\\"},{\\\"champ\\\":\\\"Type Ecran\\\",\\\"valeur\\\":\\\"\\\"},{\\\"champ\\\":\\\"Ecran Tactile\\\",\\\"valeur\\\":\\\"Non\\\"},{\\\"champ\\\":\\\"lecteurs\\\",\\\"valeur\\\":\\\"Graveur DVD\\\"},{\\\"champ\\\":\\\"Reseau\\\",\\\"valeur\\\":\\\"WiFi - Bluetooth\\\"},{\\\"champ\\\":\\\"Camera\\\",\\\"valeur\\\":\\\"\\\"},{\\\"champ\\\":\\\"Garantie\\\",\\\"valeur\\\":\\\"1 An\\\"}]'),
(3, 'HP NOTEBOOK 15-DW2011NK', 'ordinateur', ' Ecran 15.6 LED HD - Processeur Intel Core i3-1005G1, 10e Gén, up to 3.4 GHz, 4 Mo de cache - 16 Go de memoire - Disque 1 To - Carte graphique Intel UHD Graphics - Wifi - Bluetooth - 1x HDMI - 1x RJ45 - Lecteur de cartes SD - Webcam HP - Windows 10 - Garantie 1 an', 'PPC PORTABLE HP NOTEBOOK 15-DW2011NK / I3 10E GEN / 16 GO', 0, 1472, 'https://www.tunisianet.com.tn/164402-large/pc-portable-hp-notebook-15-dw2011nk-i3-10e-gen-16-go.jpg', 'https://www.tunisianet.com.tn/164399-large/pc-portable-hp-notebook-15-dw2011nk-i3-10e-gen-16-go.jpg,https://www.tunisianet.com.tn/164400-large/pc-portable-hp-notebook-15-dw2011nk-i3-10e-gen-16-go.jpg,https://www.tunisianet.com.tn/164403-large/pc-portable-hp-notebook-15-dw2011nk-i3-10e-gen-16-go.jpg,https://www.tunisianet.com.tn/164401-large/pc-portable-hp-notebook-15-dw2011nk-i3-10e-gen-16-go.jpg', '[{\\\"champ\\\":\\\"Systeme D exploitation\\\",\\\"valeur\\\":\\\"Windows 10\\\"},{\\\"champ\\\":\\\"Processeur\\\",\\\"valeur\\\":\\\"Intel Core I3\\\"},{\\\"champ\\\":\\\"Ref processeur\\\",\\\"valeur\\\":\\\"Intel Core I3-1005G1 10e Generation, 1.20 Ghz Up To 3.4 Ghz, 4 Mo De Cache\\\"},{\\\"champ\\\":\\\"memoire\\\",\\\"valeur\\\":\\\"16 Go\\\"},{\\\"champ\\\":\\\"Disque Dur\\\",\\\"valeur\\\":\\\"1 To\\\"},{\\\"champ\\\":\\\"Carte Graphique\\\",\\\"valeur\\\":\\\"Graphique Integree\\\"},{\\\"champ\\\":\\\"Ref Carte Graphique\\\",\\\"valeur\\\":\\\"Intel UHD Graphics\\\"},{\\\"champ\\\":\\\"Taille Ecran\\\",\\\"valeur\\\":\\\"15.6\\\"},{\\\"champ\\\":\\\"Type Ecran\\\",\\\"valeur\\\":\\\"HD\\\"},{\\\"champ\\\":\\\"Ecran Tactile\\\",\\\"valeur\\\":\\\"Non\\\"},{\\\"champ\\\":\\\"lecteurs\\\",\\\"valeur\\\":\\\"Lecteur De Cartes\\\"},{\\\"champ\\\":\\\"Reseau\\\",\\\"valeur\\\":\\\"WiFi - Bluetooth\\\"},{\\\"champ\\\":\\\"Camera\\\",\\\"valeur\\\":\\\"Webcam HD\\\"},{\\\"champ\\\":\\\"Garantie\\\",\\\"valeur\\\":\\\"1 An\\\"}]'),
(4, 'HUAWEI MATEBOOK D15', 'ordinateur', 'Ecran 15.6 IPS Full HD - Resolution 1920 x 1080px - Processeur AMD Ryzen R7-3700U, up to 4.0 Ghz, 4 Mo de memoire cache - Memoire 8 Go - Disque 512 Go SSD M.2 NVMe - Carte graphique AMD Radeon RX Vega 10 Graphics - 1x USB 3.0 Type C - 1x HDMI - Wifi AC - Bluetooth 5.0 - Windows 10 - Dimensions 230 x 358 x 17 mm - Poids 1.53 kg - Garantie 1 an', 'PC PORTABLEHUAWEI MATEBOOK D15 2020 / RYZEN 7 / 8 GO', 0, 1999, 'https://www.tunisianet.com.tn/184553-large/pc-portablehuawei-matebook-d15-2020-ryzen-7-8-go.jpg', 'https://www.tunisianet.com.tn/184556-large/pc-portablehuawei-matebook-d15-2020-ryzen-7-8-go.jpg,https://www.tunisianet.com.tn/184557-large/pc-portablehuawei-matebook-d15-2020-ryzen-7-8-go.jpg', '[{\\\"champ\\\":\\\"Systeme D exploitation\\\",\\\"valeur\\\":\\\"Windows 10\\\"},{\\\"champ\\\":\\\"Processeur\\\",\\\"valeur\\\":\\\"AMD Ryzen 7\\\"},{\\\"champ\\\":\\\"Ref processeur\\\",\\\"valeur\\\":\\\"AMD Ryzen 7,I7 10E GEN ,16 GO\\\"},{\\\"champ\\\":\\\"memoire\\\",\\\"valeur\\\":\\\"\\\"},{\\\"champ\\\":\\\"Disque Dur\\\",\\\"valeur\\\":\\\"8 Go\\\"},{\\\"champ\\\":\\\"Carte Graphique\\\",\\\"valeur\\\":\\\"AMD Radeon\\\"},{\\\"champ\\\":\\\"Ref Carte Graphique\\\",\\\"valeur\\\":\\\"\\\"},{\\\"champ\\\":\\\"Taille Ecran\\\",\\\"valeur\\\":\\\"15.6\\\"},{\\\"champ\\\":\\\"Type Ecran\\\",\\\"valeur\\\":\\\"Full HD\\\"},{\\\"champ\\\":\\\"Ecran Tactile\\\",\\\"valeur\\\":\\\"Non\\\"},{\\\"champ\\\":\\\"lecteurs\\\",\\\"valeur\\\":\\\"\\\"},{\\\"champ\\\":\\\"Reseau\\\",\\\"valeur\\\":\\\"WiFi - Bluetooth\\\"},{\\\"champ\\\":\\\"Camera\\\",\\\"valeur\\\":\\\"Windows 10\\\"},{\\\"champ\\\":\\\"Garantie\\\",\\\"valeur\\\":\\\"Windows 10\\\"}]'),
(5, 'HP PROBOOK 450 G7', 'ordinateur', ' Ecran 15.6 HD SVA LED - Processeur Intel Core i5-10210U, up to 4.2 GHz, 6 Mo de cache - Memoire 4 Go DDR4 2400 - Disque 500 Go - carte graphique Intel UHD 620 - Wifi 6 - Bluetooth - 1x USB 3.1 Type-C - 2x USB 3.1 - 1x USB 2.0 - HDMI 1.4b - RJ45 - Webcam 720p HD - Lecteur de cartes - Windows 10 Pro 64 - Garantie 1 an ', 'PORTABLE HP PROBOOK 450 G7 / I5 10E GEN / 4 GO', 0, 2369, 'https://www.tunisianet.com.tn/157095-large/portable-hp-probook-450-g7-i5-10e-gen-4-go-sim-orange-offerte-60-go.jpg', 'https://www.tunisianet.com.tn/157094-large/portable-hp-probook-450-g7-i5-10e-gen-4-go-sim-orange-offerte-60-go.jpg,https://www.tunisianet.com.tn/157096-large/portable-hp-probook-450-g7-i5-10e-gen-4-go-sim-orange-offerte-60-go.jpg,https://www.tunisianet.com.tn/157093-large/portable-hp-probook-450-g7-i5-10e-gen-4-go-sim-orange-offerte-60-go.jpg,https://www.tunisianet.com.tn/157097-large/portable-hp-probook-450-g7-i5-10e-gen-4-go-sim-orange-offerte-60-go.jpg', '[{\\\"champ\\\":\\\"Systeme D exploitation\\\",\\\"valeur\\\":\\\"Windows 10\\\"},{\\\"champ\\\":\\\"Processeur\\\",\\\"valeur\\\":\\\"Intel Core I5\\\"},{\\\"champ\\\":\\\"Ref processeur\\\",\\\"valeur\\\":\\\"Intel Core I5-10210U, 1.60 GHz Jusqu a 4.10 GHz, 6 Mo De Cache\\\"},{\\\"champ\\\":\\\"memoire\\\",\\\"valeur\\\":\\\"4 Go\\\"},{\\\"champ\\\":\\\"Disque Dur\\\",\\\"valeur\\\":\\\"500 Go\\\"},{\\\"champ\\\":\\\"Carte Graphique\\\",\\\"valeur\\\":\\\"Graphique Integree\\\"},{\\\"champ\\\":\\\"Ref Carte Graphique\\\",\\\"valeur\\\":\\\"Intel UHD 620\\\"},{\\\"champ\\\":\\\"Taille Ecran\\\",\\\"valeur\\\":\\\"15.6\\\"},{\\\"champ\\\":\\\"Type Ecran\\\",\\\"valeur\\\":\\\"HD\\\"},{\\\"champ\\\":\\\"Ecran Tactile\\\",\\\"valeur\\\":\\\"Non\\\"},{\\\"champ\\\":\\\"lecteurs\\\",\\\"valeur\\\":\\\"Lecteur De Cartes\\\"},{\\\"champ\\\":\\\"Reseau\\\",\\\"valeur\\\":\\\"WiFi - Bluetooth\\\"},{\\\"champ\\\":\\\"Camera\\\",\\\"valeur\\\":\\\"Webcam HD\\\"},{\\\"champ\\\":\\\"Garantie\\\",\\\"valeur\\\":\\\"Windows 10\\\"}]'),
(6, 'MSI GF63-10SCXR-1089XFR', 'ordinateur', 'Ecran 15.6 FULL HD - Processeur: Intel Core i5-10300H(2.5 GHz up to 4.5 GHz, 8 Mo de memoire cache, Quad-Core) - FreeDos - Memoire RAM: 16 Go DDR4 - Disque dur: 512 Go SSD - Carte graphique: NVIDIA GeForce GTX 1650 (Max-Q) avec (4 Go de memoire dediee GDDR5) - Clavier Retroeclaire LED Rouge - Garantie: 2 ans', 'PC PORTABLE GAMER MSI GF63 I5 10E GEN 16GO 512 GO SSD (GF63-10SCXR-1089XFR-16G)', 0, 2598, 'https://mk-media.mytek.tn/media/catalog/product/cache/8be3f98b14227a82112b46963246dfe1/b/a/bacanim1_4_1.jpg', NULL, '[{\\\"champ\\\":\\\"Systeme D exploitation\\\",\\\"valeur\\\":\\\"FreeDos\\\"},{\\\"champ\\\":\\\"Processeur\\\",\\\"valeur\\\":\\\"Intel Core i5\\\"},{\\\"champ\\\":\\\"Ref processeur\\\",\\\"valeur\\\":\\\"Intel Core i5-10300H(2.5 GHz up to 4.5 GHz, 8 Mo de memoire cache, Quad-Core)\\\"},{\\\"champ\\\":\\\"memoire\\\",\\\"valeur\\\":\\\"16 Go\\\"},{\\\"champ\\\":\\\"Disque Dur\\\",\\\"valeur\\\":\\\"512 Go SSD\\\"},{\\\"champ\\\":\\\"Carte Graphique\\\",\\\"valeur\\\":\\\"Graphique Integree\\\"},{\\\"champ\\\":\\\"Ref Carte Graphique\\\",\\\"valeur\\\":\\\"NVIDIA GeForce GTX 1650 (Max-Q) avec (4 Go de memoire dediee GDDR5)\\\"},{\\\"champ\\\":\\\"Taille Ecran\\\",\\\"valeur\\\":\\\"15.6\\\"},{\\\"champ\\\":\\\"Type Ecran\\\",\\\"valeur\\\":\\\"FULL HD\\\"},{\\\"champ\\\":\\\"Ecran Tactile\\\",\\\"valeur\\\":\\\"non\\\"},{\\\"champ\\\":\\\"lecteurs\\\",\\\"valeur\\\":\\\"\\\"},{\\\"champ\\\":\\\"Reseau\\\",\\\"valeur\\\":\\\"WiFi - Bluetooth\\\"},{\\\"champ\\\":\\\"Camera\\\",\\\"valeur\\\":\\\"\\\"},{\\\"champ\\\":\\\"Garantie\\\",\\\"valeur\\\":\\\"2 Ans\\\"}]'),
(7, 'MSI MODERN B10MW', 'ordinateur', 'Ecran 14 Full HD - Processeur Intel Core i7-10510U, up to 4.9 Ghz, 8 Mo de cache - Memoire 16 Go  - Disque 512 Go SSD - Carte graphique Intel HD Graphics - Wifi - Bluetooth - 2x USB 3.2 Type C, 2x USB 3.2 - HDMI - Lecteur de cartes - Couleur: Noir - Clavier retroeclaire - Garantie 2 ans ', 'PC PORTABLE MSI MODERN B10MW / I7 10E GEN / 16 GO / NOIR', 0, 2894, 'https://www.tunisianet.com.tn/183780-large/pc-portable-msi-modern-b10mw-i7-10e-gen-16-go-noir.jpg', 'https://www.tunisianet.com.tn/183781-large/pc-portable-msi-modern-b10mw-i7-10e-gen-16-go-noir.jpg,https://www.tunisianet.com.tn/183782-large/pc-portable-msi-modern-b10mw-i7-10e-gen-16-go-noir.jpg,https://www.tunisianet.com.tn/183783-large/pc-portable-msi-modern-b10mw-i7-10e-gen-16-go-noir.jpg,https://www.tunisianet.com.tn/183784-large/pc-portable-msi-modern-b10mw-i7-10e-gen-16-go-noir.jpg', '[{\\\"champ\\\":\\\"Systeme D exploitation\\\",\\\"valeur\\\":\\\"FreeDos\\\"},{\\\"champ\\\":\\\"Processeur\\\",\\\"valeur\\\":\\\"Intel Core I7\\\"},{\\\"champ\\\":\\\"Ref processeur\\\",\\\"valeur\\\":\\\"Intel Core I7-10510U 10e Generation , 1.8 Ghz Up To 4.9 GHz, 8 Mo De Cache\\\"},{\\\"champ\\\":\\\"memoire\\\",\\\"valeur\\\":\\\"16 Go\\\"},{\\\"champ\\\":\\\"Disque Dur\\\",\\\"valeur\\\":\\\"512 Go SSD\\\"},{\\\"champ\\\":\\\"Carte Graphique\\\",\\\"valeur\\\":\\\"Graphique Integree\\\"},{\\\"champ\\\":\\\"Ref Carte Graphique\\\",\\\"valeur\\\":\\\"Intel HD Graphics\\\"},{\\\"champ\\\":\\\"Taille Ecran\\\",\\\"valeur\\\":\\\"14\\\"},{\\\"champ\\\":\\\"Type Ecran\\\",\\\"valeur\\\":\\\"Full HD\\\"},{\\\"champ\\\":\\\"Ecran Tactile\\\",\\\"valeur\\\":\\\"Non\\\"},{\\\"champ\\\":\\\"lecteurs\\\",\\\"valeur\\\":\\\"\\\"},{\\\"champ\\\":\\\"Reseau\\\",\\\"valeur\\\":\\\"WiFi - Bluetooth\\\"},{\\\"champ\\\":\\\"Camera\\\",\\\"valeur\\\":\\\"Webcam Avec Micro\\\"},{\\\"champ\\\":\\\"Garantie\\\",\\\"valeur\\\":\\\" An\\\"}]'),
(8, 'HUAWEI MATEBOOK X PRO', 'ordinateur', ' Ecran 14 IPS 3K Tactile - Resolution 3000 x 2000px - Processeur Intel Core i7-10510U, 10e Gen, up to 4.9 Ghz, 8 Mo de memoire cache - Memoire 16 Go - Disque 1 To SSD M.2 NVMe - Carte graphique NVIDIA GeForce MX250, 2 Go de memoire DDR5 dediee - 2x USB 3.0 Type C - 1x HDMI - Wifi AC - Bluetooth 5.0 - Windows 10 - en Aluminium - Autonomie jusqu a 13 heures - Dimensions 217 x 304 x 14.6 mm - Poids 1.33 kg - Garantie 1 an + Souris Huawei  AF30 Offerte', 'PC PORTABLE HUAWEI MATEBOOK X PRO 2020 / I7 10E GEN / 16 GO / ALUMINIUM + SOURIS HUAWEI AF30 OFFERTE', 0, 5599, 'https://www.tunisianet.com.tn/184567-large/pc-portable-huawei-matebook-x-pro-2020-i7-10e-gen-16-go.jpg', 'https://www.tunisianet.com.tn/184572-large/pc-portable-huawei-matebook-x-pro-2020-i7-10e-gen-16-go.jpg,https://www.tunisianet.com.tn/184571-large/pc-portable-huawei-matebook-x-pro-2020-i7-10e-gen-16-go.jpg', '[{\\\"champ\\\":\\\"Systeme D exploitation\\\",\\\"valeur\\\":\\\"Windows 10\\\"},{\\\"champ\\\":\\\"Processeur\\\",\\\"valeur\\\":\\\"Intel Core I7\\\"},{\\\"champ\\\":\\\"Ref processeur\\\",\\\"valeur\\\":\\\"Intel Core I7-10510U 10e Generation , 1.8 Ghz Up To 4.9 GHz, 8 Mo De Cache\\\"},{\\\"champ\\\":\\\"memoire\\\",\\\"valeur\\\":\\\"8 Go\\\"},{\\\"champ\\\":\\\"Disque Dur\\\",\\\"valeur\\\":\\\"1To\\\"},{\\\"champ\\\":\\\"Carte Graphique\\\",\\\"valeur\\\":\\\"Graphique Integree\\\"},{\\\"champ\\\":\\\"Ref Carte Graphique\\\",\\\"valeur\\\":\\\"Nvidia GeForce MX250, 2 Go De Memoire Dediee\\\"},{\\\"champ\\\":\\\"Taille Ecran\\\",\\\"valeur\\\":\\\"15.6\\\"},{\\\"champ\\\":\\\"Type Ecran\\\",\\\"valeur\\\":\\\"3K\\\"},{\\\"champ\\\":\\\"Ecran Tactile\\\",\\\"valeur\\\":\\\"oui et non\\\"},{\\\"champ\\\":\\\"lecteurs\\\",\\\"valeur\\\":\\\"\\\"},{\\\"champ\\\":\\\"Reseau\\\",\\\"valeur\\\":\\\"WiFi - Bluetooth\\\"},{\\\"champ\\\":\\\"Camera\\\",\\\"valeur\\\":\\\"\\\"},{\\\"champ\\\":\\\"Garantie\\\",\\\"valeur\\\":\\\"1 An\\\"}]'),
(9, 'Clever F01', 'téléphone', 'Telephone Portable Clever F01 - Double SIM - Ecran 1.77 TFT - Mémoire 32 Mo extensible Jusqu a 16 Go via carte mémoire microSD - Batterie 800 mAh - Radio FM sans fil - Bluetooth - Camera VGA - Garantie 1 an', 'TELEPHONE PORTABLE CLEVER F01 - BLANC', 0, 49, 'https://www.tunisianet.com.tn/191465-large/telephone-portable-clever-f01-blanc.jpg', 'https://www.tunisianet.com.tn/191466-large/telephone-portable-clever-f01-blanc.jpg', '[]'),
(10, 'DORO 2404', 'téléphone', 'Telephone Portable Doro 2404 - Ecran Couleur compact 2,4 - Memoire RAM: 16 Mo - Resolution de l ecran: 320 x 240 pixels - Resolution Appareil photo numerique: 0.3 megapixels - Extension de la memoire: Micro SD - Nombre de SIM: 2 SIM, Tpe: Micro - Batterie: Li-ion 1000 mAh, Autonomie en communication: 7 h, Autonomie en veille: 450 h - Fonctions du telephone: haut parleur, compteur d appels, teleconference, mode avion, vibreur, Radio FM, bluetooth, Lampe Torche, Touche SOS - Couleur: Rouge et Blanc - Garantie 1 an', 'TELEPHONE PORTABLE DORO 2404 / DOUBLE SIM / ROUGE ET BLANC', 0, 49, 'https://www.tunisianet.com.tn/188938-large/telephone-portable-doro-2404-double-sim-rouge-et-blanc.jpg', 'https://www.tunisianet.com.tn/188940-large/telephone-portable-doro-2404-double-sim-rouge-et-blanc.jpg,https://www.tunisianet.com.tn/188939-large/telephone-portable-doro-2404-double-sim-rouge-et-blanc.jpg', '[]'),
(11, 'CONDOR GRIFFE T6', 'téléphone', ' Double SIM - Ecran 5.34 - Resolution: 480 x 960 pixels - Processeur Spreadtrum SC9850 Quad Core 1.3 Ghz - RAM 1 Go - Memoire 8 Go - Android 8.1 Oreo - 2x Appareils Photos 5 MP Arriere, 5 MP Frontale - Wifi - 4G - Bluetooth - Batterie 2500 mAh - Couleur Gris - Garantie 1 an ', 'TELEPHONE PORTABLE CONDOR GRIFFE T6 / 4G / DOUBLE SIM / GRIS', 0, 189, 'https://www.tunisianet.com.tn/136531-large/telephone-portable-condor-griffe-t6-4g-double-sim-gris.jpg', NULL, '[{\\\"champ\\\":\\\"Memoire\\\",\\\"valeur\\\":\\\"8 Go\\\"},{\\\"champ\\\":\\\"Reseau\\\",\\\"valeur\\\":\\\"4G\\\"},{\\\"champ\\\":\\\"Taille De L ecran\\\",\\\"valeur\\\":\\\"De 5 a 6\\\"},{\\\"champ\\\":\\\"Type Processeur\\\",\\\"valeur\\\":\\\"Quad Core\\\"},{\\\"champ\\\":\\\"Double SIM\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"RAM\\\",\\\"valeur\\\":\\\"1 Go\\\"},{\\\"champ\\\":\\\"Systeme\\\",\\\"valeur\\\":\\\"Android\\\"},{\\\"champ\\\":\\\"Wifi\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"Appareil Photo\\\",\\\"valeur\\\":\\\"5MP\\\"},{\\\"champ\\\":\\\"Double Camera\\\",\\\"valeur\\\":\\\"non\\\"}]'),
(12, 'CONDOR GRIFFE T9 PLUS', 'téléphone', 'Double SIM - Ecran 5.45 IPS - Resolution: 540 x 1132 pixels - Processeur Octa Core, 4x1.2 Ghz + 4x 1.6 Ghz - RAM 2 Go - Memoire 16 Go - Android 9 Pie - 2x Appareils Photos 13 MP Arriere, 8 MP Frontale - Wifi - 4G - Bluetooth - Batterie 2800 mAh - Couleur Noir - Garantie 1 an', 'TELEPHONE PORTABLE CONDOR GRIFFE T9 PLUS / 4G / DOUBLE SIM / NOIR', 0, 329, 'https://www.tunisianet.com.tn/184771-large/telephone-portable-condor-griffe-t9-plus-4g-double-sim-noir.jpg', NULL, '[{\\\"champ\\\":\\\"Memoire\\\",\\\"valeur\\\":\\\"16 Go\\\"},{\\\"champ\\\":\\\"Reseau\\\",\\\"valeur\\\":\\\"4G\\\"},{\\\"champ\\\":\\\"Taille De L ecran\\\",\\\"valeur\\\":\\\"De 5 a 6\\\"},{\\\"champ\\\":\\\"Type Processeur\\\",\\\"valeur\\\":\\\"Octa Core\\\"},{\\\"champ\\\":\\\"Double SIM\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"RAM\\\",\\\"valeur\\\":\\\"2 Go\\\"},{\\\"champ\\\":\\\"Systeme\\\",\\\"valeur\\\":\\\"Android\\\"},{\\\"champ\\\":\\\"Wifi\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"Appareil Photo\\\",\\\"valeur\\\":\\\"13MP\\\"},{\\\"champ\\\":\\\"Double Camera\\\",\\\"valeur\\\":\\\"non\\\"}]'),
(13, 'SAMSUNG GALAXY A02', 'téléphone', 'Double SIM - Ecran 6.5 HD+ - Processeur Quad Core Mediatek MT6739W 1.5 GHz, Cortex-A53 - RAM 3 Go - Memoire 32 Go - Android 10.0, One UI 2.0 - Camera arriere 13 MP, f/1.9, (wide), AF, 2 MP, f/2.4 (macro), Frontale 5 MP, f/2.0 - 4G - Wifi - Wi-Fi Direct - Bluetooth - Batterie 5000 mAh - Garantie 1 an', 'TELEPHONE PORTABLE SAMSUNG GALAXY A02 / NOIR', 0, 369, 'https://www.tunisianet.com.tn/193896-large/telephone-portable-samsung-galaxy-a02-noir.jpg', 'https://www.tunisianet.com.tn/193899-large/telephone-portable-samsung-galaxy-a02-noir.jpg,https://www.tunisianet.com.tn/193900-large/telephone-portable-samsung-galaxy-a02-noir.jpg,https://www.tunisianet.com.tn/193897-large/telephone-portable-samsung-galaxy-a02-noir.jpg,https://www.tunisianet.com.tn/193898-large/telephone-portable-samsung-galaxy-a02-noir.jpg', '[{\\\"champ\\\":\\\"Memoire\\\",\\\"valeur\\\":\\\"32 Go\\\"},{\\\"champ\\\":\\\"Reseau\\\",\\\"valeur\\\":\\\"4G\\\"},{\\\"champ\\\":\\\"Taille De L ecran\\\",\\\"valeur\\\":\\\"Superieur a 6\\\"},{\\\"champ\\\":\\\"Type Processeur\\\",\\\"valeur\\\":\\\"Quad Core\\\"},{\\\"champ\\\":\\\"Double SIM\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"RAM\\\",\\\"valeur\\\":\\\"3 Go\\\"},{\\\"champ\\\":\\\"Systeme\\\",\\\"valeur\\\":\\\"Android\\\"},{\\\"champ\\\":\\\"Wifi\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"Appareil Photo\\\",\\\"valeur\\\":\\\"13MP\\\"},{\\\"champ\\\":\\\"Double Camera\\\",\\\"valeur\\\":\\\"oui\\\"}]'),
(14, 'SAMSUNG GALAXY A12', 'téléphone', 'Double SIM - Ecran 6.5 HD+ PLS TFT LCD  (720 x 1600 px) - Processeur Octa Core 2.3 GHz - RAM 4  Go - Memoire 64 Go - Android 10 - Camera arriere Quad 48 MP + 5 MP + 2 MP + 2 MP, Camera frontale 8 MP - Lecteur d empreintes Digitales - 4G - Bluetooth - GPS - Wifi - Batterie 5000 mAh - Couleur: Noir - Garantie 1 an + Abonnement IPTV OTT Pro Offert (OTT-12M)', 'TELEPHONE PORTABLE SAMSUNG GALAXY A12 / NOIR + ABONNEMENT IPTV OTT PRO OFFERT', 0, 549, 'https://www.tunisianet.com.tn/187539-large/telephone-portable-samsung-galaxy-a12-noir.jpg', 'https://www.tunisianet.com.tn/187540-large/telephone-portable-samsung-galaxy-a12-noir.jpg,https://www.tunisianet.com.tn/187533-large/telephone-portable-samsung-galaxy-a12-noir.jpg', '[{\\\"champ\\\":\\\"Memoire\\\",\\\"valeur\\\":\\\"128 Go\\\"},{\\\"champ\\\":\\\"Reseau\\\",\\\"valeur\\\":\\\"4G\\\"},{\\\"champ\\\":\\\"Taille De L ecran\\\",\\\"valeur\\\":\\\"Superieur a 6\\\"},{\\\"champ\\\":\\\"Type Processeur\\\",\\\"valeur\\\":\\\"Octa Core\\\"},{\\\"champ\\\":\\\"Double SIM\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"RAM\\\",\\\"valeur\\\":\\\"6 Go\\\"},{\\\"champ\\\":\\\"Systeme\\\",\\\"valeur\\\":\\\"Android\\\"},{\\\"champ\\\":\\\"Wifi\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"Appareil Photo\\\",\\\"valeur\\\":\\\"48 MP\\\"},{\\\"champ\\\":\\\"Double Camera\\\",\\\"valeur\\\":\\\"oui\\\"}]'),
(15, 'HUAWEI Y8P', 'téléphone', 'Double SIM - Ecran 6.3 Full HD+ OLED - Resolution: 2400 x 1080 - Processeur: Octa Core (4x2.2 GHz Cortex-A73 + 4x1.7 GHz Cortex-A53) - Android 10 - RAM 6 Go - Memoire 128Go - Camera frontale: 16MP - Camera arriere: 48MP + 8MP + 2MP - Wifi - 4G - Bluetooth - Lecteur d empreinte Digitale integre a l ecran - Batterie 4000mAh - Couleur: Breathing Crystal - Garantie 1 an     ', 'TELEPHONE PORTABLE HUAWEI Y8P / 4G / DOUBLE SIM / BREATHING CRYSTAL', 0, 699, 'https://www.tunisianet.com.tn/164987-large/telephone-portable-huawei-y8p-4g-double-sim-breathing-crystal-sim-orange-60-go-offerte.jpg', 'https://www.tunisianet.com.tn/164989-large/telephone-portable-huawei-y8p-4g-double-sim-breathing-crystal-sim-orange-60-go-offerte.jpg,https://www.tunisianet.com.tn/164988-large/telephone-portable-huawei-y8p-4g-double-sim-breathing-crystal-sim-orange-60-go-offerte.jpg', '[{\\\"champ\\\":\\\"Memoire\\\",\\\"valeur\\\":\\\"64 Go\\\"},{\\\"champ\\\":\\\"Reseau\\\",\\\"valeur\\\":\\\"4G\\\"},{\\\"champ\\\":\\\"Taille De L ecran\\\",\\\"valeur\\\":\\\"Superieur a 6\\\"},{\\\"champ\\\":\\\"Type Processeur\\\",\\\"valeur\\\":\\\"Octa Core\\\"},{\\\"champ\\\":\\\"Double SIM\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"RAM\\\",\\\"valeur\\\":\\\"4 Go\\\"},{\\\"champ\\\":\\\"Systeme\\\",\\\"valeur\\\":\\\"Android\\\"},{\\\"champ\\\":\\\"Wifi\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"Appareil Photo\\\",\\\"valeur\\\":\\\"48 MP\\\"},{\\\"champ\\\":\\\"Double Camera\\\",\\\"valeur\\\":\\\"oui\\\"}]'),
(16, 'SAMSUNG GALAXY Z FOLD 2', 'téléphone', ' Ecran 7.7 AMOLED Infinity Flex - Resolution: (2208 x 1768 pixels) a 120 Hz - Affichage: HDR10+ - Processeur: SnapDragon 865+ (7 nm+) Octa-Core (2x2.73 GHz Mongoose M5 & 2x2.50 GHz Cortex-A76 & 4x2.0 GHz Cortex-A55) - Systeme d exploitation: Android 10 Q - Memoire RAM:12 Go - Stockage: 256 Go - Appareil Photo Arriere: Trio 12 MegaPixels f/1.8 + 12 MegaPixels f/3.0 + 12 MegaPixels f/2.2 - Appareil Photo Frontale: 10 MegaPixels - Double Sim - WiFi - 5G - Bluetooth - NFC - Capteur d empreinte digitale - Batterie: 4500 mAh - Couleur: Bronze - Garantie: 1 an ', 'TELEPHONE PORTABLE SAMSUNG GALAXY Z FOLD 2 / BRONZE', 0, 7199, 'https://www.tunisianet.com.tn/175687-large/samsung-galaxy-z-fold-2-bronze.jpg', 'https://www.tunisianet.com.tn/175688-large/samsung-galaxy-z-fold-2-bronze.jpg,https://www.tunisianet.com.tn/175685-large/samsung-galaxy-z-fold-2-bronze.jpg,https://www.tunisianet.com.tn/175684-large/samsung-galaxy-z-fold-2-bronze.jpg,https://www.tunisianet.com.tn/175686-large/samsung-galaxy-z-fold-2-bronze.jpg', '[{\\\"champ\\\":\\\"Memoire\\\",\\\"valeur\\\":\\\"256 Go\\\"},{\\\"champ\\\":\\\"Reseau\\\",\\\"valeur\\\":\\\"5G\\\"},{\\\"champ\\\":\\\"Taille De L ecran\\\",\\\"valeur\\\":\\\"Superieur a 6\\\"},{\\\"champ\\\":\\\"Type Processeur\\\",\\\"valeur\\\":\\\"Octa Core\\\"},{\\\"champ\\\":\\\"Double SIM\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"RAM\\\",\\\"valeur\\\":\\\"12 Go\\\"},{\\\"champ\\\":\\\"Systeme\\\",\\\"valeur\\\":\\\"Android\\\"},{\\\"champ\\\":\\\"Wifi\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"Appareil Photo\\\",\\\"valeur\\\":\\\"12MP\\\"},{\\\"champ\\\":\\\"Double Camera\\\",\\\"valeur\\\":\\\"oui\\\"}]'),
(17, 'CANON PIXMA G3411', 'imprimante ', 'Imprimante a reservoir integre couleur 3-en-1 - Impression, copie, scan - Resolution d impression: Jusqu a 4800 x 1200 ppp - Vitesse d impression Mono/couleur: 8.8 ipm / 5 ipm - Resolution du scanner: 600 x 1200 ppp - Format A4 - Interface: USB Haute-vitesse / Wifi - Alimentation papier standard 100 Feuilles - Dimensions: 445 x 330 x 163 mm - Poids: 6.3 Kg - Garantie 1 an + Extension de 3 ans de Garantie', 'IMPRIMANTE A RESERVOIR INTEGRE COULEUR 3-EN-1 CANON PIXMA G3411 / WIFI', 0, 549, 'https://www.tunisianet.com.tn/128139-large/imprimante-a-reservoir-integre-couleur-3-en-1-canon-pixma-g3411-wifi.jpg', 'https://www.tunisianet.com.tn/128141-large/imprimante-a-reservoir-integre-couleur-3-en-1-canon-pixma-g3411-wifi.jpg,https://www.tunisianet.com.tn/128137-large/imprimante-a-reservoir-integre-couleur-3-en-1-canon-pixma-g3411-wifi.jpg,https://www.tunisianet.com.tn/128140-large/imprimante-a-reservoir-integre-couleur-3-en-1-canon-pixma-g3411-wifi.jpg,https://www.tunisianet.com.tn/128138-large/imprimante-a-reservoir-integre-couleur-3-en-1-canon-pixma-g3411-wifi.jpg', '[{\\\"champ\\\":\\\"Type\\\",\\\"valeur\\\":\\\"Couleur\\\"},{\\\"champ\\\":\\\"Garantie\\\",\\\"valeur\\\":\\\"1 An\\\"},{\\\"champ\\\":\\\"Formats\\\",\\\"valeur\\\":\\\"A4\\\"},{\\\"champ\\\":\\\"Recto-Verso\\\",\\\"valeur\\\":\\\"non\\\"},{\\\"champ\\\":\\\"Fonctions\\\",\\\"valeur\\\":\\\"Multifonction\\\"},{\\\"champ\\\":\\\"Connectivite\\\",\\\"valeur\\\":\\\"Wifi\\\"}]'),
(18, 'HP SMART TANK 516', 'imprimante ', ' Impression, Numerisation, Copie, Sans fil (Wifi), Bluetooth- Vitesse d impression noir / couleur: Jusqu a 11 ppm / 5 ppm - Resolution d impression noir / couleur: Jusqu a 1200 x 1200 ppp - Resolution de numerisation: Jusqu a 1200 ppp - Ecran LCD 2 pouces - Interface: USB 2.0 / Wifi / Bluetooth LE - Dimensions: 449 x 605.65 x 258.7 mm - Garantie 1 an', 'IMPRIMANTE MULTIFONCTION JET D ENCRE TOUT-EN-UN HP SMART TANK 516 / WIFI', 0, 449, 'https://www.tunisianet.com.tn/164623-large/imprimante-multifonction-jet-d-encre-tout-en-un-hp-smart-tank-516-wifi.jpg', 'https://www.tunisianet.com.tn/164625-large/imprimante-multifonction-jet-d-encre-tout-en-un-hp-smart-tank-516-wifi.jpg,https://www.tunisianet.com.tn/164624-large/imprimante-multifonction-jet-d-encre-tout-en-un-hp-smart-tank-516-wifi.jpg', '[{\\\"champ\\\":\\\"Type\\\",\\\"valeur\\\":\\\"Couleur\\\"},{\\\"champ\\\":\\\"Garantie\\\",\\\"valeur\\\":\\\"1 An\\\"},{\\\"champ\\\":\\\"Formats\\\",\\\"valeur\\\":\\\"A4\\\"},{\\\"champ\\\":\\\"Recto-Verso\\\",\\\"valeur\\\":\\\"non\\\"},{\\\"champ\\\":\\\"Fonctions\\\",\\\"valeur\\\":\\\"Multifonction\\\"},{\\\"champ\\\":\\\"Connectivite\\\",\\\"valeur\\\":\\\"Wifi\\\"}]'),
(19, 'EPSON WORKFORCE PRO WF-5690DWF', 'imprimante ', 'Imprimante Multifonction Jet d encre 4 en 1 - Format A4 - Vitesse d impression noir/couleur: 34/30 ppm - Resolution d impression: 4800 x 1200 dpi (ppp) - Resolution de numerisation: 1200 x 2400 dpi - Capacite papier standard: 330 Feuilles - Interface: USB 2.0 / Ethernet / Wifi - Ecran LCD Tactile - Garantie 1 an\r\n', 'IMPRIMANTE MULTIFONCTION JET D ENCRE 4-EN-1 EPSON WORKFORCE PRO WF-5690DWF', 0, 779, 'https://www.tunisianet.com.tn/50723-large/imprimante-multifonction-jet-d-encre-4-en-1-epson-workforce-pro-wf-5690dwf.jpg', 'https://www.tunisianet.com.tn/50722-large/imprimante-multifonction-jet-d-encre-4-en-1-epson-workforce-pro-wf-5690dwf.jpg,https://www.tunisianet.com.tn/50724-large/imprimante-multifonction-jet-d-encre-4-en-1-epson-workforce-pro-wf-5690dwf.jpg', '[]'),
(20, 'HP DESIGNJET Z6DR 44', 'imprimante ', 'Imprimante Multifonction HP MFP DesignJet T830 36 - Fonction: Impression, Copie, Numerisation - Technologie: Jet D encre Thermique - Format: A0 / A1 / A2 / A3 / A4 - 4 Couleurs - Vitesse d impression: Rapide 80,5 m2/h sur support ordinaire, Normale 18,8 m2/h sur support couche, Sup: 9,7 m2/h sur support brillant - 2 Supports d impression: de 279 a 1118 mm - Resolution d impression: 2400 x 1200 DPI - Memoire: 128 Go - Langages d impression: Adobe PostScript 3, Adobe PDF 1.7, TIFF, JPEG, CALS G4, HP-GL/2, HP-RTL - Connectivite: USB, Ethernet - Dimensions: 1802 x 695 x 998 mm - Poids: 96 kg - Garantie: 1 an ', 'IMPRIMANTE HP DESIGNJET Z6DR 44 POSTSCRIPT PRINTER WITH V-TRIMMER', 0, 24715, 'https://www.tunisianet.com.tn/153887-large/imprimante-hp-designjet-z6dr-44-postscript-printer-with-v-trimmer.jpg', 'https://www.tunisianet.com.tn/153889-large/imprimante-hp-designjet-z6dr-44-postscript-printer-with-v-trimmer.jpg,https://www.tunisianet.com.tn/153888-large/imprimante-hp-designjet-z6dr-44-postscript-printer-with-v-trimmer.jpg', '[{\\\"champ\\\":\\\"Type\\\",\\\"valeur\\\":\\\"Couleur\\\"},{\\\"champ\\\":\\\"Garantie\\\",\\\"valeur\\\":\\\"1 An\\\"},{\\\"champ\\\":\\\"Formats\\\",\\\"valeur\\\":\\\"A3\\\"},{\\\"champ\\\":\\\"Recto-Verso\\\",\\\"valeur\\\":\\\"non\\\"},{\\\"champ\\\":\\\"Fonctions\\\",\\\"valeur\\\":\\\"Multifonction\\\"},{\\\"champ\\\":\\\"Connectivite\\\",\\\"valeur\\\":\\\"Wifi\\\"}]'),
(21, 'HP LaserJet Pro M130nw', 'imprimante ', 'Imprimante Multifonction 3en1 HP LaserJet Pro M130nw N&B - Impression, copie, scan - Vitesse d impression: jusqu a 22 ppm en mode normal - Resolution d impression : Jusqu a 600 x 600 ppp - Vitesse de copie: jusqu a 22 cpm - Scanner a plat Jusqu a 1 200 ppp (monochrome) - Capacite papier 100  feuilles - Interface USB 2.0 / Ethernet / Wifi - Dimensions 398 x 288 x 231,1 mm - Garantie 1 an\r\n                           ', 'IMPRIMANTE MULTIFONCTION HP LASERJET PRO M130NW NOIR&BLANC / WIFI', 0, 599, 'https://www.tunisianet.com.tn/66831-large/imprimante-multifonction-hp-laserjet-pro-m130nw-noirblanc-wifi.jpg', 'https://www.tunisianet.com.tn/66832-large/imprimante-multifonction-hp-laserjet-pro-m130nw-noirblanc-wifi.jpg,https://www.tunisianet.com.tn/66833-large/imprimante-multifonction-hp-laserjet-pro-m130nw-noirblanc-wifi.jpg', '[]'),
(22, 'SHARP MULTIFONCTION AR-B451T', 'imprimante ', 'Photocopieur Monochrome SHARP AR-B351T: Recto/Verso - Format des originaux - copies A6 - A4, Vitesse : 45 copies /mn - Memoire: 1GB - Resolution d impression: 600 X 600 DPI - Interface: Port USB 2.0 / RJ45 / CLE USB - Zoom: de 25% a 400%  - Alimentation papier: 1 Cassette de 500 feuilles - Scanner: Scanner couleur reseau, Destination Sacn: USB, Mail, Dossier Partage, FTP, Chargeur: Std de 50 feuilles, Impression: USB et reseau - direct cle usb (PDF ET JPEG) - Garantie 1 an', 'PHOTOCOPIEUR SHARP MULTIFONCTION MONOCHROME A4 AR-B451T', 0, 2499, 'https://www.tunisianet.com.tn/165259-large/photocopieur-sharp-multifonction-monochrome-a4-ar-b451t.jpg', NULL, '[{\\\"champ\\\":\\\"Type\\\",\\\"valeur\\\":\\\"Monochrome\\\"}]'),
(23, 'Toner Original LaserJet HP 128A', 'imprimante ', 'Toner Original LaserJet HP 128A - Nombre de pages imprimees: 2000 pages - Technologie d impression: Laser - Compatible avec les imprimantes laser HP CM 1415, 1415fn, 1415fnw, 1415fw, HP CP 1525, 1525n, 1525nw, HP LaserJet Pro CM1415, CM1415fn, CM1415fnw, CM1415fw, CP1525, CP1525n, CP1525nw, HP Pro 1415fnw, CM1415, CM1415fn, CM1415fw, CP1525, CP1525n, CP1525nw - Couleur: Noir', 'TONER ORIGINAL LASERJET HP 128A / NOIR', 0, 544, 'https://www.tunisianet.com.tn/161761-large/toner-original-laserjet-hp-128a-noir.jpg', NULL, '[{\\\"champ\\\":\\\"Consommable\\\",\\\"valeur\\\":\\\"Original\\\"},{\\\"champ\\\":\\\"Pack\\\",\\\"valeur\\\":\\\"Non\\\"},{\\\"champ\\\":\\\"Couleur D encre\\\",\\\"valeur\\\":\\\"Noir\\\"}]'),
(24, 'RAME PAPIER NAVIGATOR A4', 'imprimante ', 'Ramette papier explorer 100g/m2 - Format A4 - 500 papiers - Extra Blanc - Papier Lisse ', 'RAME PAPIER NAVIGATOR A4 100G/M2 / 500 FEUILLES', 0, 12, 'https://www.tunisianet.com.tn/172834-large/rame-papier-navigator-a4-100gm-500-feuilles.jpg', NULL, '[]'),
(25, 'AutoCollant Clavier Arabe', 'accessoire', 'AutoCollant Clavier Arabe - Couleur Noir', 'AutoCollant Clavier Arabe - Couleur Noir', 0, 1, 'https://www.tunisianet.com.tn/150155-large/etiquette-clavier-arabe-noir.jpg', NULL, '[]'),
(26, 'Hoco M61', 'accessoire', 'Ecouteurs stereo avec micro Hoco M61 - Gamme de frequence: 20Hz-20KHz  - Longueur de cable: 1.2m - Jack 3.5mm - Couleur Noir', 'ECOUTEURS STEREO AVEC MICRO HOCO M61 / NOIR ', 0, 9, 'https://www.tunisianet.com.tn/193302-large/ecouteurs-stereo-avec-micro-hoco-m61-noir.jpg', 'https://www.tunisianet.com.tn/193307-large/ecouteurs-stereo-avec-micro-hoco-m61-noir.jpg,https://www.tunisianet.com.tn/193303-large/ecouteurs-stereo-avec-micro-hoco-m61-noir.jpg', '[]'),
(27, 'CLAVIER QWERTY BLUETOOTH EVEREST', 'accessoire', 'Clavier Qwerty Bluetooth Everest avec TouchPad Sans Fil - Compatible avec PC / Smart TV / Console Jeux - Connexion Bluetooth - Distance de fonctionnement Maxi: 10m - Facile a Installer et Utiliser - Design Slim - Garantie 1 an', 'CLAVIER QWERTY BLUETOOTH EVEREST AVEC TOUCHPAD SANS FIL COMPATIBLE PC / SMART TV / CONSOLE JEUX ', 0, 59, 'https://www.tunisianet.com.tn/75844-large/clavier-qwerty-sans-fil-everest-avec-touchpad-compatible-pc-smart-tv-console-jeux.jpg', 'https://www.tunisianet.com.tn/75845-large/clavier-qwerty-sans-fil-everest-avec-touchpad-compatible-pc-smart-tv-console-jeux.jpg,https://www.tunisianet.com.tn/75847-large/clavier-qwerty-sans-fil-everest-avec-touchpad-compatible-pc-smart-tv-console-jeux.jpg', '[]'),
(28, 'TAPIS SOURIS GAMING', 'accessoire', 'Tapis souris Gaming Redragon Neptune XXL RGB - Effets retro-eclaires RGB avec 8 modes d eclairage differents, des effets de respiration - Surface molle est anti-eclaboussures facile a nettoyer - Fond en caoutchouc mousse naturel traite - Base en caoutchouc antiderapante - Dimensions: 800 x 300 x 3 mm - Couleur: Noir', 'TAPIS SOURIS GAMING REDRAGON NEPTUNE XXL RGB / 800 X 300', 0, 99, 'https://www.tunisianet.com.tn/153311-large/tapis-souris-gaming-jertech-mp44-35-x-44-cm.jpg', 'https://www.tunisianet.com.tn/153312-large/tapis-souris-gaming-jertech-mp44-35-x-44-cm.jpg,https://www.tunisianet.com.tn/153313-large/tapis-souris-gaming-jertech-mp44-35-x-44-cm.jpg', '[]'),
(29, 'PACK GAMER REDRAGON', 'accessoire', 'Pack Gamer REDRAGON 4 en 1 - Technologie de Connectivite: filaire - Clavier: - Interface: USB - 104 touches - 19 Touches sans conflit- 12 touches multimedia - Clavier de jeu REDRAGON LED RVB - Souris: Resolution: 3200 DPI - 6 boutons, 5 boutons programmables par l utilisateur via le logiciel - Casque: Sensibilite: 103 dB - Confort ultime pour des sessions de jeu prolongees grace aux oreillettes fermees reductrices de bruit - Interface: 3,5 mm  - Tapis de souris: Surface en tissu impermeable et traite en soie assure des mouvements de souris lisses et ultra precis -  Le dessous est fait de caoutchouc mousse traite naturel antiderapant offrant une grande flexibilite - Bord cousu - Garantie: 1 an', 'PACK GAMER REDRAGON 4EN1 CLAVIER + SOURIS + TAPIS + CASQUE ', 0, 119, 'https://mk-media.mytek.tn/media/catalog/product/cache/8be3f98b14227a82112b46963246dfe1/9/7/97941_eagmddtwfglzxmvy.jpg', NULL, '[]'),
(30, 'Huawei FreeBuds Pro', 'accessoire', 'Ecouteurs sans fil Huawei FreeBuds Pro - Processeur : Kirin A1 - Ecouteurs intra-auriculaires sans fil - 3 microphones - Transducteurs de 11 mm - Technologie Bluetooth 5.2 - Reduction de bruit active, avec annulation des bruits allant jusqu a 40 dB - Batterie : 55 mAh (par ecouteur), 580 mAh (boitier de charge) - Autonomie : 7 heures (ecoute musicale), 4 heures (appels) - Garantie 1 an', 'ECOUTEURS SANS FIL HUAWEI FREEBUDS PRO - SILVER ', 0, 699, 'https://www.tunisianet.com.tn/191595-large/ecouteurs-sans-fil-huawei-freebuds-pro-silver.jpg', 'https://www.tunisianet.com.tn/191599-large/ecouteurs-sans-fil-huawei-freebuds-pro-silver.jpg,https://www.tunisianet.com.tn/191596-large/ecouteurs-sans-fil-huawei-freebuds-pro-silver.jpg,https://www.tunisianet.com.tn/191597-large/ecouteurs-sans-fil-huawei-freebuds-pro-silver.jpg,https://www.tunisianet.com.tn/191598-large/ecouteurs-sans-fil-huawei-freebuds-pro-silver.jpg', '[]'),
(31, 'Huawei Watch GT 2 Pro Classique', 'accessoire', 'Montre connectee Huawei Watch GT 2 Pro Classique - Etanche 50 m - Ecran tactile couleur AMOLED de 1.39 pouce a resolution 454 x 454 (326 ppi) - Processeur Kirin A1 - Memoire 4 Go - Tracker d activite : 100 modes d entrainement disponibles, dont ski, golf, nation, cyclisme, course a pied, marche, rameur - Capteurs : accelerometre, gyroscope,capteur geomagnetique, capteur optique de frequence cardiaque, capteur de lumiere ambiante, barometre, capteur capacitif - Notifications : appels, SMS, emails, agenda, reseaux sociaux, applications du telephone - Connectivite : Bluetooth 5.1 - Batterie 455 mAh - Autonomie : 14 jours en utilisation standard - Tour de poignet : 140 - 210 mm - Compatible Android 5.0 et superieur / iOS 9.0 et superieur', 'MONTRE CONNECTEE HUAWEI WATCH GT 2 PRO CLASSIQUE ', 0, 1169, 'https://www.tunisianet.com.tn/191587-large/montre-connectee-huawei-watch-gt-2-pro-classique.jpg', 'https://www.tunisianet.com.tn/191583-large/montre-connectee-huawei-watch-gt-2-pro-classique.jpg,https://www.tunisianet.com.tn/191584-large/montre-connectee-huawei-watch-gt-2-pro-classique.jpg,https://www.tunisianet.com.tn/191586-large/montre-connectee-huawei-watch-gt-2-pro-classique.jpg,https://www.tunisianet.com.tn/191585-large/montre-connectee-huawei-watch-gt-2-pro-classique.jpg', '[]'),
(32, 'Samsung Galaxy Watch 3', 'accessoire', 'Montre connectee Samsung Galaxy Watch 3 - Diametre 45mm - Ecran 1.4 pouces Super AMOLED Full Color avec Gorilla Glass DX+ - Processeur Exynos 9110 Dual-Core cadence a 1.15 GHz - RAM 1 Go - Memoire 8 Go - Etanche jusqu a 50m IP68 - Connectivite: Bluetooth 5.0, Wi-Fi et NFC - Systeme Tizen 5.5 - Batterie: 340mAh, autonomie Jusqu a 56 heures - Fonctionnalites sport & bien-etre - Dimensions 46.2 x 45 x 11.1 mm - Bracelet en cuir - Garantie 1 an', 'MONTRE CONNECTEE SAMSUNG GALAXY WATCH 3 / 45MM', 0, 2739, 'https://www.tunisianet.com.tn/184404-large/montre-connectee-samsung-galaxy-watch-3-45mm.jpg', 'https://www.tunisianet.com.tn/184401-large/montre-connectee-samsung-galaxy-watch-3-45mm.jpg,https://www.tunisianet.com.tn/184400-large/montre-connectee-samsung-galaxy-watch-3-45mm.jpg,https://www.tunisianet.com.tn/184402-large/montre-connectee-samsung-galaxy-watch-3-45mm.jpg,https://www.tunisianet.com.tn/184403-large/montre-connectee-samsung-galaxy-watch-3-45mm.jpg', '[]'),
(33, 'Samsung 32 Serie 5', 'téléviseur ', 'Televiseur Samsung 32 pouces HD Serie 5 - Wifi - Resolution 1366 x 768p - 1x USB - 2x HDMI - 1x RJ45 - Type Haut Parleur: 2CH - Technologie Hyper Real - HDR -  1x entree AV, 1x entree composante (Y / Pb / Pr), 1x Sortie Audio - Game Mode - ConnectShare (USB 2.0) - Dimensions avec support: 737.4 x 438.0 x 74.1 mm - Garantie 2 ans', 'TELEVISEUR SAMSUNG 32 pouces SERIE 5 SMART TV 2020', 0, 799, 'https://www.tunisianet.com.tn/170343-large/televiseur-samsung-32-serie-5-smart-tv-2020-hd-wifi-sim-orange-60-go-offerte.jpg', 'https://www.tunisianet.com.tn/170345-large/televiseur-samsung-32-serie-5-smart-tv-2020-hd-wifi-sim-orange-60-go-offerte.jpg,https://www.tunisianet.com.tn/170344-large/televiseur-samsung-32-serie-5-smart-tv-2020-hd-wifi-sim-orange-60-go-offerte.jpg,https://www.tunisianet.com.tn/170346-large/televiseur-samsung-32-serie-5-smart-tv-2020-hd-wifi-sim-orange-60-go-offerte.jpg,https://www.tunisianet.com.tn/170342-large/televiseur-samsung-32-serie-5-smart-tv-2020-hd-wifi-sim-orange-60-go-offerte.jpg', '[{\\\"champ\\\":\\\"Taille Ecran\\\",\\\"valeur\\\":\\\"32\\\"},{\\\"champ\\\":\\\"Type Ecran\\\",\\\"valeur\\\":\\\"HD\\\"},{\\\"champ\\\":\\\"Garantie\\\",\\\"valeur\\\":\\\"2 Ans\\\"},{\\\"champ\\\":\\\"Wifi\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"Smart TV\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"TV Incurvee\\\",\\\"valeur\\\":\\\"Non\\\"},{\\\"champ\\\":\\\"Recepteur Integre\\\",\\\"valeur\\\":\\\"Non\\\"}]'),
(34, 'Samsung 43 Serie 5', 'téléviseur ', 'Televiseur Samsung 43 pouces Full HD Serie 5 - Resolution 1920 x 1080p - 1x USB - 2x HDMI - Haut Parleur 20W (2x 10W) - Tuner analogique - DVB-T/S2 - 1x entree AV, 1x entree composante (Y / Pb / Pr), 1x Sortie Audio - ConnectShare (USB 2.0) - Dimensions avec support 979.9 x 596.6 x 170.3 mm - Garantie 2 ans', 'TELEVISEUR SAMSUNG 43 FULL HD SERIE 5 ', 0, 1299, 'https://www.tunisianet.com.tn/160757-large/televiseur-samsung-43-full-hd-serie-5-sim-orange-offerte-60-go.jpg', 'https://www.tunisianet.com.tn/160755-large/televiseur-samsung-43-full-hd-serie-5-sim-orange-offerte-60-go.jpg,https://www.tunisianet.com.tn/160756-large/televiseur-samsung-43-full-hd-serie-5-sim-orange-offerte-60-go.jpg,https://www.tunisianet.com.tn/160757-large/televiseur-samsung-43-full-hd-serie-5-sim-orange-offerte-60-go.jpg,https://www.tunisianet.com.tn/160758-large/televiseur-samsung-43-full-hd-serie-5-sim-orange-offerte-60-go.jpg', '[{\\\"champ\\\":\\\"Taille Ecran\\\",\\\"valeur\\\":\\\"43\\\"},{\\\"champ\\\":\\\"Type Ecran\\\",\\\"valeur\\\":\\\"Full HD\\\"},{\\\"champ\\\":\\\"Garantie\\\",\\\"valeur\\\":\\\"2 Ans\\\"},{\\\"champ\\\":\\\"Wifi\\\",\\\"valeur\\\":\\\"Non\\\"},{\\\"champ\\\":\\\"Smart TV\\\",\\\"valeur\\\":\\\"Non\\\"},{\\\"champ\\\":\\\"TV Incurvee\\\",\\\"valeur\\\":\\\"Non\\\"},{\\\"champ\\\":\\\"Recepteur Integre\\\",\\\"valeur\\\":\\\"Non\\\"}]'),
(35, 'LG 65 4K', 'téléviseur ', 'Televiseur 65 pouces LED UHD 4k + Recepteur integre - Resolution 3840 x 2160 - Smart TV ThinQ AI - Processeur Quad Core - Angle de vision Large - HDR Pro - Puissance Audio: 20W / 2.0 canaux - Jeux HDR - DVR Numerique - Wifi - Bluetooth - 3x HDMI - RJ45 - 2x USB - Teletexte 2000 Pages - Montage VESA200 x 200 - Alimentation: CA 100 ~ 240V 50-60Hz - Dimensions: 1463 x 850 x 87.8 mm - Garantie: 2 ans + Commande Smart + Recepteur integre ', 'TELEVISEUR LG 65 LED UHD 4K / SMART TV / WIFI / + COMMANDE SMART + RECEPTEUR INTEGRE ', 0, 3899, 'https://www.tunisianet.com.tn/172014-large/televiseur-lg-65-led-uhd-4k-smart-tv-wifi-commande-smart-recepteur-integre-sim-orange-offerte-60-go.jpg', 'https://www.tunisianet.com.tn/172015-large/televiseur-lg-65-led-uhd-4k-smart-tv-wifi-commande-smart-recepteur-integre-sim-orange-offerte-60-go.jpg,https://www.tunisianet.com.tn/172018-large/televiseur-lg-65-led-uhd-4k-smart-tv-wifi-commande-smart-recepteur-integre-sim-orange-offerte-60-go.jpg', '[{\\\"champ\\\":\\\"Taille Ecran\\\",\\\"valeur\\\":\\\"65\\\"},{\\\"champ\\\":\\\"Type Ecran\\\",\\\"valeur\\\":\\\"4K\\\"},{\\\"champ\\\":\\\"Garantie\\\",\\\"valeur\\\":\\\"2 Ans\\\"},{\\\"champ\\\":\\\"Wifi\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"Smart TV\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"TV Incurvee\\\",\\\"valeur\\\":\\\"Non\\\"},{\\\"champ\\\":\\\"Recepteur Integre\\\",\\\"valeur\\\":\\\"Oui\\\"}]'),
(36, 'Samsung 82 Serie 8', 'téléviseur ', 'Televiseur Samsung 82 pouces Full HD Serie 8 - Wifi - Resolution 3840 x 2160p - 1x USB - 3x HDMI - 1x RJ45 - Bluetooth - 1x entree AV - 1x sortie audio - Processeur Crystal 4K - Type Haut Parleur: 2CH - Mode ambiant - Technologie Hyper Real - HDR 10+ - OS Tizen™ - PurColor - UHD Dimming ,Partage d ecran Mobile vers TV - Dolby Digital Plus ,Tuner analogique - DVB -T2CS2 - Dimensions: 1829,9 x 1148,2 x 392,2 mm - Poids: 38,9 kg - Couleur: Noir - Garantie 2 ans', 'TELEVISEUR SAMSUNG 82 SERIE 8 CRYSTAL UHD 4K / SMART TV 2020 / WIFI', 0, 12999, 'https://www.tunisianet.com.tn/172360-large/televiseur-samsung-82-serie-8-crystal-uhd-4k-smart-tv-2020-wifi-sim-orange-60-go-offerte.jpg', 'https://www.tunisianet.com.tn/172364-large/televiseur-samsung-82-serie-8-crystal-uhd-4k-smart-tv-2020-wifi-sim-orange-60-go-offerte.jpg,https://www.tunisianet.com.tn/172361-large/televiseur-samsung-82-serie-8-crystal-uhd-4k-smart-tv-2020-wifi-sim-orange-60-go-offerte.jpg,https://www.tunisianet.com.tn/172363-large/televiseur-samsung-82-serie-8-crystal-uhd-4k-smart-tv-2020-wifi-sim-orange-60-go-offerte.jpg,https://www.tunisianet.com.tn/172362-large/televiseur-samsung-82-serie-8-crystal-uhd-4k-smart-tv-2020-wifi-sim-orange-60-go-offerte.jpg', '[{\\\"champ\\\":\\\"Taille Ecran\\\",\\\"valeur\\\":\\\"82\\\"},{\\\"champ\\\":\\\"Type Ecran\\\",\\\"valeur\\\":\\\"4K\\\"},{\\\"champ\\\":\\\"Garantie\\\",\\\"valeur\\\":\\\"2 Ans\\\"},{\\\"champ\\\":\\\"Wifi\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"Smart TV\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"TV Incurvee\\\",\\\"valeur\\\":\\\"Non\\\"},{\\\"champ\\\":\\\"Recepteur Integre\\\",\\\"valeur\\\":\\\"Non\\\"}]'),
(37, 'VEGA 32', 'téléviseur ', 'Televiseur VEGA 32 pouces HD LED - Resolution 1366 x 768 - RAM 1 Go - Memoire 8 Go - Android 7.1 Nougat - Aspect ratio 16:9 - Luminosite: 200 cd/m2 - Contraste 3000:1 - Angle de vue: 178 x 178 - Maximum colors 16.7M - Temps de reponse 6.5 ms - Sortie Audio: 2x 8W - 1x Reseau Ethernet - 3x HDMI - 1x VGA - 2x USB - Dimensions sans support 720.2 x 422.8 x 77.6 mm - Couleur Noir - Garantie 3 ans', 'TELEVISEUR VEGA 32 HD LED / SMART TV / ANDROID + RECEPTEUR INTEGRE', 0, 619, 'https://www.tunisianet.com.tn/182320-large/televiseur-vega-32-hd-led-smart-tv-android-recepteur-integre.jpg', 'https://www.tunisianet.com.tn/182321-large/televiseur-vega-32-hd-led-smart-tv-android-recepteur-integre.jpg,https://www.tunisianet.com.tn/182323-large/televiseur-vega-32-hd-led-smart-tv-android-recepteur-integre.jpg', '[{\\\"champ\\\":\\\"Taille Ecran\\\",\\\"valeur\\\":\\\"32\\\"},{\\\"champ\\\":\\\"Type Ecran\\\",\\\"valeur\\\":\\\"HD\\\"},{\\\"champ\\\":\\\"Garantie\\\",\\\"valeur\\\":\\\"3 Ans\\\"},{\\\"champ\\\":\\\"Wifi\\\",\\\"valeur\\\":\\\"Non\\\"},{\\\"champ\\\":\\\"Smart TV\\\",\\\"valeur\\\":\\\"Oui\\\"},{\\\"champ\\\":\\\"TV Incurvee\\\",\\\"valeur\\\":\\\"Non\\\"},{\\\"champ\\\":\\\"Recepteur Integre\\\",\\\"valeur\\\":\\\"Oui\\\"}]'),
(38, 'SUPPORT MURAL ONYX', 'téléviseur ', 'Support mural Onyx pour TV LED / LCD - Adapte pour les televiseurs de 14 pouces a 46 pouces - Permet de fixer en toute securite un ecran plat au mur - Structure en acier renforce - Installation fixe et compacte, materiel ideal pour la maison, le bureau ou les boutiques des detaillants - Poids max. : 50 Kg - Kit de fixation inclus - Garantie 1 an', 'SUPPORT MURAL ONYX POUR TV LED / LCD 14-46', 0, 39, 'https://www.tunisianet.com.tn/60845-large/support-mural-onyx-pour-tv-led-lcd-14-46.jpg', 'https://www.tunisianet.com.tn/60846-large/support-mural-onyx-pour-tv-led-lcd-14-46.jpg,https://www.tunisianet.com.tn/60848-large/support-mural-onyx-pour-tv-led-lcd-14-46.jpg', '[]'),
(39, 'SUPPORT MURAL EVEREST TK-10', 'téléviseur ', ' Support Mural Everest TK-10 Pour Televiseur LED / LCD - Supporte Televiseurs: 32 pouces jusqu a 55 pouces', 'SUPPORT MURAL EVEREST TK-10 POUR TELEVISEUR 32-55', 0, 15, 'https://www.tunisianet.com.tn/138606-large/support-mural-everest-tk-10-pour-televiseur-32-55.jpg', NULL, '[]'),
(40, 'SUPPORT MURAL SBOX', 'téléviseur ', 'Support Mural Pour Televiseur SBOX PLB-2264F - Taille de l ecran: 37 pouces - 70 pouces / 94 - 177 cm - Poids maximum du moniteur: 35 kg - Distance du mur: 19.5 mm - Montage: VESA 75x75 / VESA 600x400 - Garantie 1 an', 'SUPPORT MURAL POUR TELEVISEUR SBOX PLB-2264F / 37-70', 0, 42, 'https://www.tunisianet.com.tn/72997-large/support-mural-pour-televiseur-sbox-plb-2264f-37-70.jpg', 'https://www.tunisianet.com.tn/72998-large/support-mural-pour-televiseur-sbox-plb-2264f-37-70.jpg,https://www.tunisianet.com.tn/72999-large/support-mural-pour-televiseur-sbox-plb-2264f-37-70.jpg', '[]');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `client`
--
ALTER TABLE `client`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `num-téléphone_UNIQUE` (`ntelephone`),
  ADD UNIQUE KEY `id_UNIQUE` (`id`),
  ADD UNIQUE KEY `email_UNIQUE` (`email`);

--
-- Index pour la table `commande`
--
ALTER TABLE `commande`
  ADD PRIMARY KEY (`commande_id`),
  ADD KEY `référence_idx` (`référence`),
  ADD KEY `CIN_idx` (`id`);

--
-- Index pour la table `produit`
--
ALTER TABLE `produit`
  ADD PRIMARY KEY (`référence`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `client`
--
ALTER TABLE `client`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT pour la table `commande`
--
ALTER TABLE `commande`
  MODIFY `commande_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT pour la table `produit`
--
ALTER TABLE `produit`
  MODIFY `référence` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=41;

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `commande`
--
ALTER TABLE `commande`
  ADD CONSTRAINT `CIN` FOREIGN KEY (`id`) REFERENCES `client` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `référence` FOREIGN KEY (`référence`) REFERENCES `produit` (`référence`) ON DELETE NO ACTION ON UPDATE NO ACTION;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
